name: PR Build (actions/regex-validator)

permissions:
  contents: read

on:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/__pr-build-actions-regex-validator.yml
      - .github/workflows/npm-build-test-public.yml
      - actions/regex-validator/**

jobs:

  pr-build:
    uses: ritterim/public-github-actions/.github/workflows/npm-build-test-public.yml@v1.8.0
    with:
      project_directory: actions/regex-validator/
      run_tests: true
